# Run as Administrator. Native output is retained privately and summarized.
# No service changes. Existing per-batch state is reused on subsequent runs.
[CmdletBinding()]
param([string]$ReplayRoot = 'C:\soc-lab\benign-replay')
$ErrorActionPreference = 'Stop'
$oldPassword = $env:SOC_LAB_ES_PASSWORD

function Get-SafeLogSummary([string[]]$Paths) {
    $errors = 0
    $warnings = 0
    $dropped = 0
    foreach ($path in $Paths) {
        if (-not (Test-Path -LiteralPath $path)) { continue }
        foreach ($line in [IO.File]::ReadLines($path)) {
            try { $row = $line | ConvertFrom-Json -ErrorAction Stop } catch { continue }
            if ($row.'log.level' -eq 'error' -or $row.level -eq 'error') { $errors++ }
            if ($row.'log.level' -eq 'warn' -or $row.level -eq 'warn') { $warnings++ }
            $value = $row.monitoring.metrics.libbeat.output.events.dropped
            if ($null -ne $value -and [long]$value -gt $dropped) { $dropped = [long]$value }
        }
    }
    return [pscustomobject]@{Errors=$errors; Warnings=$warnings; DroppedObserved=$dropped}
}

function Invoke-Beat([string]$Exe, [string[]]$Arguments, [string]$OutPath, [string]$ErrPath) {
    # Own the process handle directly. Windows PowerShell 5.1 Start-Process
    # redirection can otherwise return an object with a null ExitCode.
    $info = New-Object Diagnostics.ProcessStartInfo
    $info.FileName = $Exe
    $info.Arguments = $Arguments -join ' '
    $info.UseShellExecute = $false
    $info.CreateNoWindow = $true
    $info.RedirectStandardOutput = $true
    $info.RedirectStandardError = $true
    $process = New-Object Diagnostics.Process
    $process.StartInfo = $info
    $outFile = $null
    $errFile = $null
    try {
        $outFile = [IO.File]::Open($OutPath, 'Create', 'Write', 'Read')
        $errFile = [IO.File]::Open($ErrPath, 'Create', 'Write', 'Read')
        if (-not $process.Start()) { throw 'Native process could not be started.' }
        # Drain both pipes concurrently; reading just one can deadlock.
        $outCopy = $process.StandardOutput.BaseStream.CopyToAsync($outFile)
        $errCopy = $process.StandardError.BaseStream.CopyToAsync($errFile)
        $watch = [Diagnostics.Stopwatch]::StartNew()
        $nextReport = 30
        while (-not $process.WaitForExit(1000)) {
            if ($watch.Elapsed.TotalSeconds -ge $nextReport) {
                Write-Host ('  Running: {0:N0} seconds elapsed' -f $watch.Elapsed.TotalSeconds)
                $nextReport += 30
            }
        }
        $process.WaitForExit()
        $null = $outCopy.GetAwaiter().GetResult()
        $null = $errCopy.GetAwaiter().GetResult()
        return [int]$process.ExitCode
    } finally {
        if ($null -ne $outFile) { $outFile.Dispose() }
        if ($null -ne $errFile) { $errFile.Dispose() }
        $process.Dispose()
    }
}

try {
    $principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw 'Run this replay from Administrator PowerShell.'
    }
    $exe = 'C:\soc-lab\winlogbeat\winlogbeat.exe'
    if (-not (Test-Path -LiteralPath $exe)) { throw 'Winlogbeat executable missing.' }
    $checkOut = Join-Path $ReplayRoot 'launcher-self-check-out.txt'
    $checkErr = Join-Path $ReplayRoot 'launcher-self-check-err.txt'
    $checkCode = Invoke-Beat (Join-Path $env:SystemRoot 'System32\cmd.exe') `
        @('/d', '/c', 'exit', '7') $checkOut $checkErr
    if ($checkCode -ne 7) { throw "Launcher self-check failed: expected exit 7; received $checkCode." }
    Write-Host 'Launcher self-check passed: expected exit 7; received 7.'
    $plan = Get-Content -LiteralPath (Join-Path $ReplayRoot 'replay-manifest.json') -Raw | ConvertFrom-Json
    $secrets = Get-Content -LiteralPath (Join-Path $ReplayRoot 'connection-secrets.json') -Raw | ConvertFrom-Json
    $env:SOC_LAB_ES_PASSWORD = [string]$secrets.password
    $secrets = $null
    if (-not $env:SOC_LAB_ES_PASSWORD) { throw 'Local connection password missing.' }
    # Exclusive launcher lock prevents overlapping replay jobs.
    $lock = [IO.File]::Open((Join-Path $ReplayRoot 'launcher.lock'), 'OpenOrCreate', 'ReadWrite', 'None')
    $total = @($plan.batches).Count
    Write-Host "Replay plan: $($plan.files) files in $total batches."
    $index = 0
    foreach ($batch in $plan.batches) {
        $index++
        $done = Join-Path $batch.state 'replay-complete.json'
        if (Test-Path -LiteralPath $done) {
            Write-Host "[$index/$total] $($batch.id): already completed; skipped."
            continue
        }
        Write-Host "[$index/$total] $($batch.id): $($batch.files) files."
        # Paths generated by the helper are under C:\soc-lab and contain no spaces.
        $common = @('-c', $batch.config, '--path.home', 'C:\soc-lab\winlogbeat',
                    '--path.data', $batch.state, '--path.logs', $batch.logs, '-e')
        $testOut = Join-Path $batch.logs 'config-test-out.txt'
        $testErr = Join-Path $batch.logs 'config-test-err.txt'
        $exitCode = Invoke-Beat $exe (@('test', 'config') + $common) $testOut $testErr
        Write-Host "  Config test exit=$exitCode"
        if ($exitCode -ne 0) {
            throw "Config check failed for $($batch.id); exit=$exitCode. Raw diagnostic output retained locally."
        }
        $stamp = [DateTime]::UtcNow.ToString('yyyyMMdd-HHmmss')
        $outPath = Join-Path $batch.logs "replay-$stamp-out.txt"
        $errPath = Join-Path $batch.logs "replay-$stamp-err.txt"
        $exitCode = Invoke-Beat $exe (@('run') + $common) $outPath $errPath
        $summary = Get-SafeLogSummary @($outPath, $errPath)
        Write-Host "  exit=$exitCode errors=$($summary.Errors) warnings=$($summary.Warnings) dropped-observed=$($summary.DroppedObserved)"
        if ($exitCode -ne 0 -or $summary.Errors -gt 0 -or $summary.DroppedObserved -gt 0) {
            throw "Replay needs review at $($batch.id). Paste only this summary; keep raw diagnostic logs local."
        }
        [pscustomobject]@{Batch=$batch.id; Files=$batch.files; ExitCode=$exitCode;
            Warnings=$summary.Warnings; CompletedUtc=[DateTime]::UtcNow.ToString('o')} |
            ConvertTo-Json | Set-Content -LiteralPath $done -Encoding UTF8
    }
    Write-Host 'REPLAY JOBS COMPLETE. Elasticsearch counts and telemetry coverage still need verification.'
} catch {
    Write-Host ('STOPPED: ' + $_.Exception.Message)
    exit 1
} finally {
    if ($null -ne $lock) { $lock.Dispose() }
    $env:SOC_LAB_ES_PASSWORD = $oldPassword
}
